config/routes.rb
Rails.application.routes.draw do
  resources :password_resets,     only: [:new, :create, :edit, :update]
  namespace :static_pages do
    get :home
  end
  get 'help' => 'static_pages#help'
  root 'static_pages#home'
  resources :microposts,          only: [:create, :destroy]
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'signup'  => 'users#new'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <!--
   the CSS id error_explanation for use in styling the error messages. (CSS uses the pound sign # to style ids.)
   after an invalid submission Rails automatically wraps the fields with errors in divs with the CSS class field_with_errors
   -->
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <!-- what is ol? -->
    <ol class="microposts">
      <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<!--
    Note the inclusion of
        html: { multipart: true }
    in the arguments to form_for, which is necessary for file uploads.
-->

<%= form_for(@micropost, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
      <!-- The valid formats consist of the MIME types accepted by the validation (by using the accept) -->
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
<% end %>

<!-- this is actually a jquery -->
<script type="text/javascript">
    // the micropost_picture is the id of the <f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'> above
    $('#micropost_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<!-- current_user is a method defined in SessionHelper -->
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>